name: rigel_fyp_project
description: A new Flutter project

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  firebase_core: ^1.10.2
  firebase_auth: ^3.3.0
  cloud_firestore: ^3.1.1
  flutter_font_icons: ^2.2.4
  bottom_navy_bar: ^6.0.0
  expandable: ^5.0.1
  google_fonts: ^2.1.0
  wc_form_validators: ^1.0.0
  flutter_form_builder: ^7.0.0
  image_picker: ^0.8.4+7
  provider: ^6.0.2
  flutter_typeahead: ^3.2.4
  flutter_chat_ui: ^1.1.0
  mime: ^1.0.1
  file_picker: ^4.3.3
  uuid: ^3.0.5
  open_file: ^3.2.1
  firebase_storage: ^9.0.0
  shared_preferences: ^2.0.13
  bubble: ^1.2.1
  device_preview: ^1.0.0
  transparent_image: ^2.0.0
  animations: ^2.0.2
  textfield_tags: ^1.4.2
  flutter_rating_bar: ^4.0.0
  percent_indicator: ^4.0.0
  path: ^1.8.0
  favorite_button: ^0.0.4
  web3dart: ^2.0.0
  velocity_x: ^3.4.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/assets/logo.png"


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/images/
     - assets/icons/
     - assets/
